Repository project-codeflare/codeflare-sdk, pull requests merged in 2024-08, with the labels that each got.

#614 Add Ray Cluster Upgrade test of Ray Job Long Running scenarios
  tests/e2e/mnist_sleep.py
  tests/upgrade/raycluster_sdk_upgrade_sleep_test.py
Labels: lgtm

#640 Upgrade tests: Make sure head node has enough memory to execute test
  tests/upgrade/raycluster_sdk_upgrade_test.py
Labels: approved, lgtm

#641 Explicitly define setuptools dependency to fix odh-notebooks-sync workflow
  poetry.lock
  pyproject.toml
Labels: approved, lgtm

#642 Allow setuptools to use previous versions for compatibility
  poetry.lock
  pyproject.toml
Labels: approved, lgtm

#646 Increase memory for ray head pod
  tests/e2e/mnist_raycluster_sdk_oauth_test.py
Labels: approved, lgtm

#647 Update notebooks and docs with updated Cluster Configuration args
  demo-notebooks/additional-demos/hf_interactive.ipynb
  demo-notebooks/additional-demos/local_interactive.ipynb
  demo-notebooks/additional-demos/ray_job_client.ipynb
  demo-notebooks/guided-demos/0_basic_ray.ipynb
  demo-notebooks/guided-demos/1_cluster_job_client.ipynb
  demo-notebooks/guided-demos/2_basic_interactive.ipynb
  demo-notebooks/guided-demos/notebook-ex-outputs/0_basic_ray.ipynb
  demo-notebooks/guided-demos/notebook-ex-outputs/1_cluster_job_client.ipynb
  demo-notebooks/guided-demos/notebook-ex-outputs/2_basic_interactive.ipynb
  demo-notebooks/guided-demos/preview_nbs/0_basic_ray.ipynb
  demo-notebooks/guided-demos/preview_nbs/1_cluster_job_client.ipynb
  demo-notebooks/guided-demos/preview_nbs/2_basic_interactive.ipynb
  docs/cluster-configuration.md
Labels: approved, lgtm, test-guided-notebooks

#648 RHOAIENG-10371 - Clean up content of cells in SDK demo notebooks
  demo-notebooks/additional-demos/hf_interactive.ipynb
  demo-notebooks/additional-demos/local_interactive.ipynb
  demo-notebooks/additional-demos/ray_job_client.ipynb
  demo-notebooks/guided-demos/1_cluster_job_client.ipynb
  demo-notebooks/guided-demos/notebook-ex-outputs/0_basic_ray.ipynb
  demo-notebooks/guided-demos/notebook-ex-outputs/1_cluster_job_client.ipynb
  demo-notebooks/guided-demos/notebook-ex-outputs/2_basic_interactive.ipynb
  demo-notebooks/guided-demos/preview_nbs/1_cluster_job_client.ipynb
Labels: approved, lgtm, test-guided-notebooks
