Repository project-codeflare/codeflare-sdk, pull requests merged in 2024-10, with the labels that each got.

#690 remove installation of packages in nb sync
  .github/workflows/odh-notebooks-sync.yml
Labels: approved, lgtm

#694 Use default image in UI notebook tests
  .github/workflows/ui_notebooks_test.yaml
Labels: approved, lgtm, test-ui-notebooks

#692 [Part-1] Refactor k8s related code into a separate module
  .gitignore
  poetry.lock
  src/codeflare_sdk.egg-info/SOURCES.txt
  src/codeflare_sdk/__init__.py
  src/codeflare_sdk/cluster/__init__.py
  src/codeflare_sdk/cluster/awload.py
  src/codeflare_sdk/cluster/cluster.py
  src/codeflare_sdk/cluster/widgets.py
  src/codeflare_sdk/common/__init__.py
  src/codeflare_sdk/common/kubernetes_cluster/__init__.py
  src/codeflare_sdk/common/kubernetes_cluster/auth.py
  src/codeflare_sdk/common/kubernetes_cluster/kube_api_helpers.py
  src/codeflare_sdk/utils/generate_cert.py
  src/codeflare_sdk/utils/generate_yaml.py
  tests/e2e/support.py
  tests/unit_test.py
  tests/upgrade/raycluster_sdk_upgrade_sleep_test.py
  tests/upgrade/raycluster_sdk_upgrade_test.py
Labels: approved, lgtm, test-guided-notebooks

#696 Refactor Kueue module
  src/codeflare_sdk/common/kueue/__init__.py
  src/codeflare_sdk/common/kueue/kueue.py
  src/codeflare_sdk/ray/cluster/generate_yaml.py
  tests/unit_test.py
Labels: approved, lgtm, test-guided-notebooks

#693 Add codecov for unit test coverage
  .github/workflows/unit-tests.yml
Labels: approved, lgtm

#700 fix: skip_tls authentication functionality
  src/codeflare_sdk/common/kubernetes_cluster/auth.py
Labels: approved, lgtm

#704 bugfix: int being interpreted directly to bytes not GB
  src/codeflare_sdk/ray/cluster/config.py
Labels: approved, lgtm

#705 Dynamic notebooks sync workflow
  .github/workflows/odh-notebooks-sync.yml
Labels: approved, lgtm

#712 Add ChristianZaccaria to Approvers and Ygnas to Reviewers
  OWNERS
Labels: approved, lgtm

#710 add function for listing lqs by flavors
  src/codeflare_sdk/__init__.py
  src/codeflare_sdk/common/kubernetes_cluster/kube_api_helpers.py
  src/codeflare_sdk/common/kueue/__init__.py
  src/codeflare_sdk/common/kueue/kueue.py
  src/codeflare_sdk/common/kueue/test_kueue.py
Labels: approved, lgtm

#713 fix: publish documentation workflow
  .github/workflows/release.yaml
Labels: approved, lgtm

#714 Pull latest changes before syncing to notebooks
  .github/workflows/odh-notebooks-sync.yml
Labels: approved, lgtm

#719 Apply Workaround for SDK e2e tests to avoid SSL error
  tests/e2e/local_interactive_sdk_oauth_test.py
  tests/e2e/mnist_raycluster_sdk_oauth_test.py
  tests/upgrade/raycluster_sdk_upgrade_test.py
Labels: approved, lgtm

#723 fix: copy_demo_nbs function package path
  src/codeflare_sdk/common/utils/demos.py
Labels: approved, lgtm

#732 fix: update the snapshot to match the latest changes
  ui-tests/tests/widget_notebook_example.test.ts-snapshots/widgets-cell-2-linux.png
Labels: approved, lgtm, test-ui-notebooks, e2e

#724 hi PR
  .github/workflows/guided_notebook_tests.yaml
Labels: approved, lgtm

#737 Test PR
  .github/workflows/dependabot-labeler.yaml
  .github/workflows/ui_notebooks_test.yaml
Labels: approved, lgtm, dependabot

#739 Test PR
  .github/workflows/guided_notebook_tests.yaml
Labels: approved, lgtm, dependabot

#740 Fix dependabot labeler and workflows
  .github/dependabot.yml
  .github/workflows/dependabot-labeler.yaml
  .github/workflows/e2e_tests.yaml
  .github/workflows/guided_notebook_tests.yaml
  .github/workflows/pre-commit.yaml
  .github/workflows/ui_notebooks_test.yaml
  .github/workflows/unit-tests.yml
Labels: approved, lgtm

#745 codecov wasn't being updated on main
  .github/workflows/unit-tests.yml
Labels: approved, lgtm

#718 e2e test for heterogenous cluster
  .github/workflows/e2e_tests.yaml
  tests/e2e/heterogeneous_clusters_kind_test.py
  tests/e2e/heterogeneous_clusters_oauth_test.py
  tests/e2e/support.py
Labels: approved, lgtm
