Repository project-codeflare/codeflare-sdk, pull requests merged in 2024-07, with the labels that each got.

#577 Added Varsha to OWNERS file
  OWNERS
Labels: approved, lgtm

#547 update SDK args
  src/codeflare_sdk/cluster/cluster.py
  src/codeflare_sdk/cluster/config.py
  src/codeflare_sdk/utils/generate_yaml.py
  tests/e2e/local_interactive_sdk_kind_test.py
  tests/e2e/local_interactive_sdk_oauth_test.py
  tests/e2e/mnist_raycluster_sdk_kind_test.py
  tests/e2e/mnist_raycluster_sdk_oauth_test.py
  tests/e2e/start_ray_cluster.py
  tests/unit_test.py
  tests/unit_test_support.py
  tests/upgrade/raycluster_sdk_upgrade_test.py
Labels: approved, lgtm

#581 Remove Anish from reviewers
  OWNERS
Labels: approved, lgtm

#582 Updated image parameter to be optional
  src/codeflare_sdk/cluster/cluster.py
  src/codeflare_sdk/utils/generate_yaml.py
  tests/unit_test.py
Labels: approved, lgtm

#531 simplify function calls and add option for custom resources
  src/codeflare_sdk/cluster/cluster.py
  src/codeflare_sdk/cluster/config.py
  src/codeflare_sdk/cluster/model.py
  src/codeflare_sdk/templates/base-template.yaml
  src/codeflare_sdk/utils/generate_yaml.py
  src/codeflare_sdk/utils/pretty_print.py
  tests/e2e/local_interactive_sdk_kind_test.py
  tests/e2e/local_interactive_sdk_oauth_test.py
  tests/e2e/mnist_raycluster_sdk_kind_test.py
  tests/e2e/mnist_raycluster_sdk_oauth_test.py
  tests/e2e/start_ray_cluster.py
  tests/test-case-bad.yaml
  tests/test-case-no-kueue-no-aw.yaml
  tests/test-case-no-mcad.yamls
  tests/test-case.yaml
  tests/test-default-appwrapper.yaml
  tests/unit_test.py
  tests/unit_test_support.py
  tests/upgrade/raycluster_sdk_upgrade_test.py
Labels: approved, lgtm

#575 Added support for checking version of the codeflare-sdk package
  src/codeflare_sdk/__init__.py
Labels: approved, lgtm

#583 [RHOAIENG-9004] Adjust e2e tests to use GPU
  .github/workflows/e2e_tests.yaml
  docs/e2e.md
  pyproject.toml
  tests/e2e/local_interactive_sdk_kind_test.py
  tests/e2e/mnist.py
  tests/e2e/mnist_raycluster_sdk_aw_kind_test.py
  tests/e2e/mnist_raycluster_sdk_kind_test.py
  tests/e2e/support.py
Labels: approved, lgtm

#585 Increase Cluster configuration memory for upgrade tests
  tests/upgrade/raycluster_sdk_upgrade_test.py
Labels: lgtm

#592 Remove Dependabot
  .github/dependabot.yml
Labels: approved, lgtm

#586 Update cluster configuration to increase worker memory and remove ray…
  tests/e2e/local_interactive_sdk_kind_test.py
  tests/e2e/local_interactive_sdk_oauth_test.py
  tests/e2e/mnist_raycluster_sdk_aw_kind_test.py
  tests/e2e/mnist_raycluster_sdk_kind_test.py
  tests/e2e/mnist_raycluster_sdk_oauth_test.py
Labels: approved, lgtm

#572 Update existing tests for disconnected automation
  .pre-commit-config.yaml
  docs/e2e.md
  tests/e2e/local_interactive_sdk_oauth_test.py
  tests/e2e/minio_deployment.yaml
  tests/e2e/mnist.py
  tests/e2e/mnist_pip_requirements.txt
  tests/e2e/mnist_raycluster_sdk_aw_kind_test.py
  tests/e2e/mnist_raycluster_sdk_kind_test.py
  tests/e2e/mnist_raycluster_sdk_oauth_test.py
  tests/e2e/support.py
  tests/upgrade/raycluster_sdk_upgrade_test.py
Labels: lgtm

#598 Update unit tests for RHOAI ray image
  tests/test-case-custom-image.yaml
  tests/unit_test.py
  tests/unit_test_support.py
Labels: approved, lgtm

#597 rm default namespace from demo notebooks
  demo-notebooks/additional-demos/hf_interactive.ipynb
  demo-notebooks/additional-demos/local_interactive.ipynb
  demo-notebooks/additional-demos/ray_job_client.ipynb
  demo-notebooks/guided-demos/0_basic_ray.ipynb
  demo-notebooks/guided-demos/1_cluster_job_client.ipynb
  demo-notebooks/guided-demos/2_basic_interactive.ipynb
  demo-notebooks/guided-demos/notebook-ex-outputs/0_basic_ray.ipynb
  demo-notebooks/guided-demos/notebook-ex-outputs/1_cluster_job_client.ipynb
  demo-notebooks/guided-demos/notebook-ex-outputs/2_basic_interactive.ipynb
  demo-notebooks/guided-demos/preview_nbs/0_basic_ray.ipynb
  demo-notebooks/guided-demos/preview_nbs/1_cluster_job_client.ipynb
  demo-notebooks/guided-demos/preview_nbs/2_basic_interactive.ipynb
Labels: approved, lgtm

#606 Adding tls cert creation and updating num workers in hf notebook
  demo-notebooks/additional-demos/hf_interactive.ipynb
Labels: approved, lgtm

#595 Run PR check for guided notebooks
  .github/resources/minio_remote_config_cell.json
  .github/resources/wait_for_job_cell.json
  .github/workflows/guided_notebook_tests.yaml
  demo-notebooks/guided-demos/0_basic_ray.ipynb
  demo-notebooks/guided-demos/1_cluster_job_client.ipynb
  demo-notebooks/guided-demos/2_basic_interactive.ipynb
  demo-notebooks/guided-demos/mnist_fashion.py
  tests/e2e/minio_deployment.yaml
Labels: approved, lgtm, test-guided-notebooks

#605 mv demo nbs into src folder and add fn for cloning to current dir
  README.md
  src/codeflare_sdk/__init__.py
  src/codeflare_sdk/demo-notebooks/additional-demos/hf_interactive.ipynb
  src/codeflare_sdk/demo-notebooks/additional-demos/local_interactive.ipynb
  src/codeflare_sdk/demo-notebooks/additional-demos/ray_job_client.ipynb
  src/codeflare_sdk/demo-notebooks/guided-demos/0_basic_ray.ipynb
  src/codeflare_sdk/demo-notebooks/guided-demos/1_cluster_job_client.ipynb
  src/codeflare_sdk/demo-notebooks/guided-demos/2_basic_interactive.ipynb
  src/codeflare_sdk/demo-notebooks/guided-demos/download_mnist_datasets.py
  src/codeflare_sdk/demo-notebooks/guided-demos/mnist.py
  src/codeflare_sdk/demo-notebooks/guided-demos/mnist_disconnected.py
  src/codeflare_sdk/demo-notebooks/guided-demos/mnist_fashion.py
  src/codeflare_sdk/demo-notebooks/guided-demos/notebook-ex-outputs/0_basic_ray.ipynb
  src/codeflare_sdk/demo-notebooks/guided-demos/notebook-ex-outputs/1_cluster_job_client.ipynb
  src/codeflare_sdk/demo-notebooks/guided-demos/notebook-ex-outputs/2_basic_interactive.ipynb
  src/codeflare_sdk/demo-notebooks/guided-demos/notebook-ex-outputs/interactivetest.yaml
  src/codeflare_sdk/demo-notebooks/guided-demos/notebook-ex-outputs/jobtest.yaml
  src/codeflare_sdk/demo-notebooks/guided-demos/notebook-ex-outputs/mnist.py
  src/codeflare_sdk/demo-notebooks/guided-demos/notebook-ex-outputs/raytest.yaml
  src/codeflare_sdk/demo-notebooks/guided-demos/notebook-ex-outputs/requirements.txt
  src/codeflare_sdk/demo-notebooks/guided-demos/preview_nbs/0_basic_ray.ipynb
  src/codeflare_sdk/demo-notebooks/guided-demos/preview_nbs/1_cluster_job_client.ipynb
  src/codeflare_sdk/demo-notebooks/guided-demos/preview_nbs/2_basic_interactive.ipynb
  src/codeflare_sdk/demo-notebooks/guided-demos/preview_nbs/mnist.py
  src/codeflare_sdk/demo-notebooks/guided-demos/preview_nbs/requirements.txt
  src/codeflare_sdk/demo-notebooks/guided-demos/requirements.txt
  src/codeflare_sdk/utils/demos.py
Labels: approved, lgtm

#594 Make ray image parameter as optional
  docs/cluster-configuration.md
  src/codeflare_sdk/demo-notebooks/additional-demos/hf_interactive.ipynb
  src/codeflare_sdk/demo-notebooks/additional-demos/local_interactive.ipynb
  src/codeflare_sdk/demo-notebooks/additional-demos/ray_job_client.ipynb
  src/codeflare_sdk/demo-notebooks/guided-demos/0_basic_ray.ipynb
  src/codeflare_sdk/demo-notebooks/guided-demos/1_cluster_job_client.ipynb
  src/codeflare_sdk/demo-notebooks/guided-demos/2_basic_interactive.ipynb
  src/codeflare_sdk/demo-notebooks/guided-demos/notebook-ex-outputs/0_basic_ray.ipynb
  src/codeflare_sdk/demo-notebooks/guided-demos/notebook-ex-outputs/1_cluster_job_client.ipynb
  src/codeflare_sdk/demo-notebooks/guided-demos/notebook-ex-outputs/2_basic_interactive.ipynb
  src/codeflare_sdk/demo-notebooks/guided-demos/preview_nbs/0_basic_ray.ipynb
  src/codeflare_sdk/demo-notebooks/guided-demos/preview_nbs/1_cluster_job_client.ipynb
  src/codeflare_sdk/demo-notebooks/guided-demos/preview_nbs/2_basic_interactive.ipynb
Labels: approved, lgtm

#609 Fixed automated documentation
  .github/workflows/release.yaml
  demo-notebooks/additional-demos/hf_interactive.ipynb
  demo-notebooks/additional-demos/local_interactive.ipynb
  demo-notebooks/additional-demos/ray_job_client.ipynb
  demo-notebooks/guided-demos/0_basic_ray.ipynb
  demo-notebooks/guided-demos/1_cluster_job_client.ipynb
  demo-notebooks/guided-demos/2_basic_interactive.ipynb
  demo-notebooks/guided-demos/download_mnist_datasets.py
  demo-notebooks/guided-demos/mnist.py
  demo-notebooks/guided-demos/mnist_disconnected.py
  demo-notebooks/guided-demos/mnist_fashion.py
  demo-notebooks/guided-demos/notebook-ex-outputs/0_basic_ray.ipynb
  demo-notebooks/guided-demos/notebook-ex-outputs/1_cluster_job_client.ipynb
  demo-notebooks/guided-demos/notebook-ex-outputs/2_basic_interactive.ipynb
  demo-notebooks/guided-demos/notebook-ex-outputs/interactivetest.yaml
  demo-notebooks/guided-demos/notebook-ex-outputs/jobtest.yaml
  demo-notebooks/guided-demos/notebook-ex-outputs/mnist.py
  demo-notebooks/guided-demos/notebook-ex-outputs/raytest.yaml
  demo-notebooks/guided-demos/notebook-ex-outputs/requirements.txt
  demo-notebooks/guided-demos/preview_nbs/0_basic_ray.ipynb
  demo-notebooks/guided-demos/preview_nbs/1_cluster_job_client.ipynb
  demo-notebooks/guided-demos/preview_nbs/2_basic_interactive.ipynb
  demo-notebooks/guided-demos/preview_nbs/mnist.py
  demo-notebooks/guided-demos/preview_nbs/requirements.txt
  demo-notebooks/guided-demos/requirements.txt
Labels: approved, lgtm

#610 Fixed copy demo notebooks in automated documentation
  .github/workflows/release.yaml
Labels: approved, lgtm

#608 Adjust demo notebooks path for guided notebooks PR check
  README.md
  demo-notebooks/guided-demos/2_basic_interactive.ipynb
Labels: approved, lgtm, test-guided-notebooks
