Repository project-codeflare/codeflare-sdk, pull requests merged in 2024-04, with the labels that each got.

#480 Remove creation of OAuth resources/logic and remove openshift_oauth option
  src/codeflare_sdk/cluster/cluster.py
  src/codeflare_sdk/cluster/config.py
  src/codeflare_sdk/utils/generate_yaml.py
  src/codeflare_sdk/utils/openshift_oauth.py
  tests/e2e/mnist_raycluster_sdk_oauth_test.py
  tests/unit_test.py
  tests/unit_test_support.py
Labels: approved, lgtm

#495 Remove ingress/routes logic from SDK
  .github/workflows/e2e_tests.yaml
  src/codeflare_sdk/cluster/cluster.py
  src/codeflare_sdk/cluster/config.py
  src/codeflare_sdk/templates/base-template.yaml
  src/codeflare_sdk/utils/generate_yaml.py
  tests/e2e/mnist_raycluster_sdk_test.py
  tests/e2e/start_ray_cluster.py
  tests/test-case-no-mcad.yamls
  tests/test-case-prio.yaml
  tests/test-case.yaml
  tests/test-default-appwrapper.yaml
  tests/unit_test.py
  tests/unit_test_support.py
Labels: approved

#499 remove: GPT guided demo
  demo-notebooks/guided-demos/4_gpt.ipynb
  demo-notebooks/guided-demos/gpt_og.py
  demo-notebooks/guided-demos/notebook-ex-outputs/4_gpt.ipynb
  demo-notebooks/guided-demos/notebook-ex-outputs/gpt_og.py
  demo-notebooks/guided-demos/notebook-ex-outputs/gptfttest.yaml
  demo-notebooks/guided-demos/notebook-ex-outputs/requirements_gpt.txt
  demo-notebooks/guided-demos/preview_nbs/4_gpt.ipynb
  demo-notebooks/guided-demos/preview_nbs/gpt_og.py
  demo-notebooks/guided-demos/preview_nbs/requirements_gpt.txt
  demo-notebooks/guided-demos/requirements_gpt.txt
Labels: approved, lgtm

#502 fix: use quay for images
  src/codeflare_sdk/templates/base-template.yaml
Labels: approved, lgtm

#503 Changes in docs for release: v0.15.0
  docs/detailed-documentation/cluster/cluster.html
  docs/detailed-documentation/cluster/config.html
  docs/detailed-documentation/cluster/index.html
  docs/detailed-documentation/cluster/model.html
  docs/detailed-documentation/index.html
  docs/detailed-documentation/job/index.html
  docs/detailed-documentation/job/jobs.html
  docs/detailed-documentation/utils/generate_yaml.html
  docs/detailed-documentation/utils/index.html
  docs/detailed-documentation/utils/openshift_oauth.html
  docs/detailed-documentation/utils/pretty_print.html
Labels: approved, lgtm

#507 Bug-fix wait_ready functionality
  src/codeflare_sdk/cluster/cluster.py
Labels: approved, lgtm

#508 Fix RBAC for e2e tests
  .github/workflows/e2e_tests.yaml
Labels: lgtm

#511 Changes in docs for release: v0.15.1
  docs/detailed-documentation/cluster/cluster.html
Labels: approved, lgtm

#510 Update e2e.test workflow
  .github/workflows/e2e_tests.yaml
Labels: approved, lgtm

#505 Refactor e2e tests to use kueue
  docs/e2e.md
  tests/e2e/kueue_resources_setup.sh
  tests/e2e/mnist_raycluster_sdk_kind_test.py
  tests/e2e/mnist_raycluster_sdk_oauth_test.py
  tests/e2e/support.py
Labels: lgtm

#514 remove print of auth header
  src/codeflare_sdk/cluster/cluster.py
Labels: approved, lgtm

#516 Fix Notebook sync release workflow trigger
  .github/workflows/release.yaml
Labels: approved, lgtm

#517 Changes in docs for release: v0.16.0
  docs/detailed-documentation/cluster/cluster.html
  docs/detailed-documentation/cluster/config.html
  docs/detailed-documentation/utils/generate_yaml.html
Labels: approved, lgtm

#519 Use stronger runner for Notebook sync workflow
  .github/workflows/odh-notebooks-sync.yml
Labels: approved, lgtm

#522 use parse_quantity to convert string to raw resource
  src/codeflare_sdk/cluster/cluster.py
  src/codeflare_sdk/cluster/config.py
  src/codeflare_sdk/utils/generate_yaml.py
  src/codeflare_sdk/utils/pretty_print.py
  tests/unit_test.py
Labels: lgtm
